services:

  swyno-backend:
    container_name: swyno-backend
    image: satangozo/swyno-backend:${TAG}
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: swyno-backend.dockerfile
      args:
        TAG: ${TAG}
    ports:
      - 8081:3000
    volumes:
      - ./volumes/swyno-backend/database/:/app/database/
    networks:
      - swyno-network

  swyno-frontend:
    container_name: swyno-frontend
    image: satangozo/swyno-frontend:${TAG}
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: swyno-frontend.dockerfile
      args:
        TAG: ${TAG}
    ports:
      - 8080:4200
    networks:
      - swyno-network
    depends_on:
      - swyno-backend

networks:
  swyno-network:
    driver: bridge
