version: '3'

services:

  swyno-backend:
    container_name: swyno-backend
    build:
      context: .
      dockerfile: swyno-backend.dockerfile
    ports:
      - 8081:3000
    volumes:
      - ./volumes/swyno-backend/database/:/app/database/
    networks:
      - swyno-network

  swyno-frontend:
    container_name: swyno-frontend
    build:
      context: .
      dockerfile: swyno-frontend.dockerfile
    ports:
      - 8080:4200
    networks:
      - swyno-network
    depends_on:
      - swyno-backend

networks:
  swyno-network:
    driver: bridge
